# Hands-On Session

**Workflow for this Hands-On Session**

1. Write Python code to solve the programming questions
2. All the questions are based on what we have already questioned
3. Solutions to all the questions are available in the Solutions.ipynb Jupyter notebook
4. It is highly encouraged to solve the programming questionnaires on your own even though you can refer to the solutions

**Q1. Write a NumPy program to generate five random numbers**

In [13]:
import numpy as np
x = np.random.random(5)
print(x)

[0.9402507  0.68508718 0.80041955 0.83829767 0.16024923]


**Q2. Write a NumPy program to generate six random integers between 10 and 30**

In [14]:
import numpy as np
x = np.random.randint(low=10, high=30, size=6)
print(x)

[18 24 19 22 11 17]


**Q3. Create a 4X2 integer array and prints the following attributes**    
  
**1.The shape of an array.**  
**2. Array dimensions.**  
**3. The Length of each element of the array in bytes.**  

In [19]:
import numpy

firstArray = numpy.empty([4, 2], dtype=numpy.uint16)
print("Printing Array")
print(firstArray)

print("Printing numpy array Attributes")
print("1> Array Shape is: ", firstArray.shape)
print("2>. Array dimensions are ", firstArray.ndim)
print("3>. Length of each element of array in bytes is ", firstArray.itemsize)

Printing Array
[[38704  4771]
 [  453     0]
 [12784  4772]
 [  453     0]]
Printing numpy array Attributes
1> Array Shape is:  (4, 2)
2>. Array dimensions are  2
3>. Length of each element of array in bytes is  2


**Q4. Create a 5X2 integer array from a range between 100 to 200 such that the difference between each element is 10**

In [20]:
import numpy

print("Creating 5X2 array using numpy.arange")
sampleArray = numpy.arange(100, 200, 10)
sampleArray = sampleArray.reshape(5, 2)
print(sampleArray)

Creating 5X2 array using numpy.arange
[[100 110]
 [120 130]
 [140 150]
 [160 170]
 [180 190]]


**Q5. Following is the provided numPy array.**     
**Return array of items in the third column from all rows**  
  
**import numpy**  
**sampleArray = numpy.array([[11 ,22, 33], [44, 55, 66], [77, 88, 99]])**    

In [26]:
import numpy

sampleArray = numpy.array([[11, 22, 33], [44, 55, 66], [77, 88, 99]])
print("Printing Input Array")
print(sampleArray)
print("\n Printing array of items in the third column from all rows")
newArray = sampleArray[..., 2]
print(newArray)

Printing Input Array
[[11 22 33]
 [44 55 66]
 [77 88 99]]

 Printing array of items in the third column from all rows
[33 66 99]


**Q6. Create an 8X3 integer array from a range between 10 to 34 such that the difference between each element is 1 and then Split the array into four equal-sized sub-arrays.**

In [29]:
import numpy

print("Creating 8X3 array using numpy.arange")
sampleArray = numpy.arange(10, 34, 1)
sampleArray = sampleArray.reshape(8, 3)
print(sampleArray)
print("\nDividing 8X3 array into 4 sub array\n")
subArrays = numpy.split(sampleArray, 4)
print(subArrays)

Creating 8X3 array using numpy.arange
[[10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]
 [22 23 24]
 [25 26 27]
 [28 29 30]
 [31 32 33]]

Dividing 8X3 array into 4 sub array

[array([[10, 11, 12],
       [13, 14, 15]]), array([[16, 17, 18],
       [19, 20, 21]]), array([[22, 23, 24],
       [25, 26, 27]]), array([[28, 29, 30],
       [31, 32, 33]])]


**Q7. Following is the input for NumPy array**  
**Delete column two and insert following new column in its place.**  

**import numpy**  
**sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]])**  
**newColumn = numpy.array([[10,10,10]])**  

In [30]:
import numpy

print("Printing Original array")
sampleArray = numpy.array([[34, 43, 73], [82, 22, 12], [53, 94, 66]])
print(sampleArray)
print("Array after deleting column 2 on axis 1")
sampleArray = numpy.delete(sampleArray, 1, axis=1)
print(sampleArray)

arr = numpy.array([[10, 10, 10]])
print("Array after inserting column 2 on axis 1")
sampleArray = numpy.insert(sampleArray, 1, arr, axis=1)
print(sampleArray)

Printing Original array
[[34 43 73]
 [82 22 12]
 [53 94 66]]
Array after deleting column 2 on axis 1
[[34 73]
 [82 12]
 [53 66]]
Array after inserting column 2 on axis 1
[[34 10 73]
 [82 10 12]
 [53 10 66]]


**Q8. How to find the memory size of any array?**

In [31]:
Z = np.zeros((10,10))
print("%d bytes" % (Z.size * Z.itemsize))

800 bytes


**Q9. Create a null vector of size 10 but the fifth value which is 1.**

In [32]:
Z = np.zeros(10)
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


**Q10. Create a vector with values ranging from 10 to 49.**

In [33]:
Z = np.arange(10,50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


**Q11. Reverse a vector (first element becomes last)**

In [34]:
Z = np.arange(50)
Z = Z[::-1]
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


**Q12. Create a 3x3 matrix with values ranging from 0 to 8.**

In [35]:
Z = np.arange(9).reshape(3,3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


**Q13. Find indices of non-zero elements from [1,2,0,0,4,0]**

In [39]:
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4], dtype=int64),)


**Q14. Create a 3x3 identity matrix**

In [40]:
Z = np.eye(3)
print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


**Q15. Create a 3x3x3 array with random values.**

In [41]:
Z = np.random.random((3,3,3))
print(Z)

[[[0.42458972 0.15321683 0.10579664]
  [0.97491914 0.16864634 0.5419839 ]
  [0.12242218 0.4925354  0.85239182]]

 [[0.97003337 0.7719112  0.03094   ]
  [0.58060085 0.20077985 0.80804828]
  [0.10667436 0.77441668 0.13675612]]

 [[0.94486584 0.41239964 0.09164415]
  [0.09848032 0.53350251 0.4040563 ]
  [0.51949301 0.91425288 0.82820144]]]


**Q16. Create a random vector of size 30 and find the mean value.**

In [42]:
Z = np.random.random(30)
m = Z.mean()
print(m)

0.38385116983345285


**Q17. Guess the results of the following expressions?**  
**print(0 * np.nan)**  
**print(np.nan == np.nan)  
print(np.inf > np.nan)  
print(np.nan - np.nan)  
print(np.nan in set([np.nan]))  
print(0.3 == 3 * 0.1)**  

In [53]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


**Q17. Create a 8x8 matrix and fill it with a checkerboard pattern.**

In [54]:
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


**Q18. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)**

In [55]:
Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


**Q19. What is the output of the following code?**

In [56]:
import numpy as np
print(np.sum(range(5)))
print(np.sum(range(5)))

10
10


**Q20. What are the result of the following expressions?**

In [58]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))

nan
0


C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


**Q21. Create a random vector of size 10 and sort it.**

In [60]:
import pprint as pp
Z = np.random.random(10)
Z.sort()
pp.pprint(Z)

array([0.02456688, 0.05628845, 0.18371428, 0.31036359, 0.31099722,
       0.39655368, 0.40416857, 0.42204991, 0.59723876, 0.73867757])


**Q22. How to get the positions where elements of two arrays match?**    
**a = np.array([1,2,3,2,3,4,3,4,5,6])**    
**b = np.array([7,2,10,2,7,4,9,4,9,8])**    

In [62]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a == b)
#> (array([1, 3, 5, 7]),)

(array([1, 3, 5, 7], dtype=int64),)

**How to get the positions where elements of two arrays match?**  
**a = np.array([1,2,3,2,3,4,3,4,5,6])**  
**b = np.array([7,2,10,2,7,4,9,4,9,8])**  

In [63]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.where(a == b)
#> (array([1, 3, 5, 7]),)

(array([1, 3, 5, 7], dtype=int64),)

**Q23. How to extract all numbers between a given range from a numpy array?**    
**a = np.array([2, 6, 1, 9, 10, 3, 27])**  
**index = np.where((a >= 5) & (a <= 10))**  
**a[index]**

In [67]:
a = np.array([2, 6, 1, 9, 10, 3, 27])
index = np.where((a >= 5) & (a <= 10))
a[index]

array([ 6,  9, 10])

**Q24. How to reverse the columns of a 2D array?**  
**arr = np.arange(9).reshape(3,3)**  

In [68]:
arr = np.arange(9).reshape(3,3)
arr[:, ::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

**Q25. How to limit the number of items printed in output of numpy array?**  
**a = np.arange(15)**

In [69]:
np.set_printoptions(threshold=6)
a = np.arange(15)
a

array([ 0,  1,  2, ..., 12, 13, 14])

**Q25. Import pandas under the name pd.**

In [85]:
import pandas as pd

 **Q26. Print the version of pandas that has been imported.**

In [86]:
pd.__version__

'0.25.0'

**Q27. Print out all the version information of the libraries that are required by the pandas library.**

In [87]:
print(pd.show_versions())


INSTALLED VERSIONS
------------------
commit           : None
python           : 3.7.3.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
machine          : AMD64
processor        : Intel64 Family 6 Model 61 Stepping 4, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : None.None

pandas           : 0.25.0
numpy            : 1.16.2
pytz             : 2018.9
dateutil         : 2.8.0
pip              : 19.0.3
setuptools       : 40.8.0
Cython           : 0.29.6
pytest           : 4.3.1
hypothesis       : None
sphinx           : 1.8.5
blosc            : None
feather          : None
xlsxwriter       : 1.1.5
lxml.etree       : 4.3.2
html5lib         : 1.0.1
pymysql          : None
psycopg2         : None
jinja2           : 2.10
IPython          : 7.4.0
pandas_datareader: None
bs4              : 4.7.1
bottleneck       : 1.2.1
fastparquet      : None
gcsfs            : None
lxml.etree       : 4.3.2
matplotlib  

In [94]:
import numpy as np
# Consider the following Python dictionary data and Python list labels:

data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

**Q28. Create a DataFrame df from this dictionary data which has the index labels.**

In [95]:
df = pd.DataFrame(data, index=labels)
print(df)

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  2.0       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no


**Q29. Display a summary of the basic information about this DataFrame and its data.**

In [96]:
df.info()

# ...or...
print("\n")

df.describe()

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, a to j
Data columns (total 4 columns):
animal      10 non-null object
age         8 non-null float64
visits      10 non-null int64
priority    10 non-null object
dtypes: float64(1), int64(1), object(2)
memory usage: 400.0+ bytes




age     visits
count  8.000000  10.000000
mean   3.437500   1.900000
std    2.007797   0.875595
min    0.500000   1.000000
25%    2.375000   1.000000
50%    3.000000   2.000000
75%    4.625000   2.750000
max    7.000000   3.000000

**Q30. Return the first 3 rows of the DataFrame df.**

In [97]:
df.iloc[:3]

# or equivalently

df.head(3) 

animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no

**Q31. Select just the 'animal' and 'age' columns from the DataFrame df.**

In [99]:
df.loc[:, ['animal', 'age']]

# or

df[['animal', 'age']]

animal  age
a    cat  2.5
b    cat  3.0
c  snake  0.5
d    dog  NaN
e    dog  5.0
f    cat  2.0
g  snake  4.5
h    cat  NaN
i    dog  7.0
j    dog  3.0

**Q32. Select the data in rows [3, 4, 8] and in columns ['animal', 'age'].**

In [102]:
df.loc[df.index[[3, 4, 8]], ['animal', 'age']]

animal  age
d    dog  NaN
e    dog  5.0
i    dog  7.0

**Q33. Select only the rows where the number of visits is greater than 3.**

In [104]:
df[df['visits'] > 2]

animal  age  visits priority
b    cat  3.0       3      yes
d    dog  NaN       3      yes
f    cat  2.0       3       no

**Q34. Select the rows where the age is missing, i.e. is NaN.**

In [105]:
df[df['age'].isnull()]

animal  age  visits priority
d    dog  NaN       3      yes
h    cat  NaN       1      yes

**Q35. Select the rows where the animal is a cat and the age is less than 3.**

In [106]:
df[(df['animal'] == 'cat') & (df['age'] < 3)]

animal  age  visits priority
a    cat  2.5       1      yes
f    cat  2.0       3       no

**Q36. Select the rows the age is between 2 and 4 (inclusive).**

In [107]:
df[df['age'].between(2, 4)]

animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
f    cat  2.0       3       no
j    dog  3.0       1       no

**Q37. Change the age in row 'f' to 1.5.**

In [109]:
df.loc['f', 'age'] = 1.5
df

animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  1.5       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no

**Q38. Calculate the sum of all visits (the total number of visits).**

In [110]:
df['visits'].sum()

19

**Q38. Calculate the mean age for each different animal in df.**

In [111]:
df.groupby('animal')['age'].mean()

animal
cat      2.333333
dog      5.000000
snake    2.500000
Name: age, dtype: float64

**Q39. Append a new row 'k' to df with your choice of values for each column. Then delete that row to return the original DataFrame.**

In [115]:
df.loc['k'] = [5.5, 'dog', 'no', 2]
print(df)
print("\n")
# deleting the new row...
df = df.drop('k')
print(df)

  animal  age visits priority
a    cat  2.5      1      yes
b    cat    3      3      yes
c  snake  0.5      2       no
d    dog  NaN      3      yes
e    dog    5      2       no
f    cat  1.5      3       no
g  snake  4.5      1       no
h    cat  NaN      1      yes
i    dog    7      2       no
j    dog    3      1       no
k    5.5  dog     no        2


  animal  age visits priority
a    cat  2.5      1      yes
b    cat    3      3      yes
c  snake  0.5      2       no
d    dog  NaN      3      yes
e    dog    5      2       no
f    cat  1.5      3       no
g  snake  4.5      1       no
h    cat  NaN      1      yes
i    dog    7      2       no
j    dog    3      1       no


 **Q40. Count the number of each type of animal in df.**

In [116]:
df['animal'].value_counts()

dog      4
cat      4
snake    2
Name: animal, dtype: int64

**Q41. Sort df first by the values in the 'age' in decending order, then by the value in the 'visit' column in ascending order.**

In [117]:
df.sort_values(by=['age', 'visits'], ascending=[False, True])

animal  age visits priority
i    dog    7      2       no
e    dog    5      2       no
g  snake  4.5      1       no
j    dog    3      1       no
b    cat    3      3      yes
a    cat  2.5      1      yes
f    cat  1.5      3       no
c  snake  0.5      2       no
h    cat  NaN      1      yes
d    dog  NaN      3      yes

**Q42. The 'priority' column contains the values 'yes' and 'no'. Replace this column with a column of boolean values: 'yes' should be True and 'no' should be False.**

In [119]:
df['priority'] = df['priority'].map({'yes': True, 'no': False})
df

animal  age visits priority
a    cat  2.5      1      NaN
b    cat    3      3      NaN
c  snake  0.5      2      NaN
d    dog  NaN      3      NaN
e    dog    5      2      NaN
f    cat  1.5      3      NaN
g  snake  4.5      1      NaN
h    cat  NaN      1      NaN
i    dog    7      2      NaN
j    dog    3      1      NaN

 **Q43. In the 'animal' column, change the 'snake' entries to 'python'.**

In [120]:
df['animal'] = df['animal'].replace('snake', 'python')
df

animal  age visits priority
a     cat  2.5      1      NaN
b     cat    3      3      NaN
c  python  0.5      2      NaN
d     dog  NaN      3      NaN
e     dog    5      2      NaN
f     cat  1.5      3      NaN
g  python  4.5      1      NaN
h     cat  NaN      1      NaN
i     dog    7      2      NaN
j     dog    3      1      NaN

**Q44. A DataFrame has a column of groups 'grps' and and column of numbers 'vals'. For example:**  

```df = pd.DataFrame(  
    {  
        "grps": list("aaabbcaabcccbbc"),  
        "vals": [12, 345, 3, 1, 45, 14, 4, 52, 54, 23, 235, 21, 57, 3, 87],  
    }  
)```  

**For each group, find the sum of the three greatest values.**  

In [124]:
df = pd.DataFrame(
    {
        "grps": list("aaabbcaabcccbbc"),
        "vals": [12, 345, 3, 1, 45, 14, 4, 52, 54, 23, 235, 21, 57, 3, 87],
    }
)
df.groupby("grps")["vals"].nlargest(3).sum(level=0)

grps
a    409
b    156
c    345
Name: vals, dtype: int64